# Generated by Django 5.0.14 on 2026-06-23 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('report_type', models.CharField(choices=[('stock_summary', 'Resumo de Estoque'), ('low_stock', 'Estoque Baixo'), ('expiry', 'Validade'), ('movement', 'Movimentações'), ('sales_forecast', 'Previsão de Vendas'), ('ai_custom', 'Relatório IA Personalizado'), ('supplier_performance', 'Desempenho de Fornecedores')], max_length=30, verbose_name='Tipo')),
                ('content', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('summary', models.TextField(blank=True, verbose_name='Resumo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('generated_by', models.CharField(default='system', max_length=50, verbose_name='Gerado por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ['-created_at'],
            },
        ),
    ]
