# Generated by Django 5.0.14 on 2026-06-23 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('low_stock', 'Estoque Baixo'), ('expiry', 'Vencimento Proximo'), ('expired', 'Produto Vencido'), ('billing', 'Cobranca'), ('system', 'Sistema'), ('ai_report', 'Relatorio IA'), ('purchase_order', 'Pedido de Compra')], default='system', max_length=30, verbose_name='Tipo')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('danger', 'Critico')], default='info', max_length=20, verbose_name='Severidade')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL de acao')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Notificacoes por email')),
                ('low_stock_alerts', models.BooleanField(default=True, verbose_name='Alertas de estoque baixo')),
                ('expiry_alerts', models.BooleanField(default=True, verbose_name='Alertas de vencimento')),
                ('daily_summary', models.BooleanField(default=False, verbose_name='Resumo diario')),
                ('weekly_report', models.BooleanField(default=True, verbose_name='Relatorio semanal')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Configuracao de Notificacoes',
                'verbose_name_plural': 'Configuracoes de Notificacoes',
            },
        ),
    ]
