# Generated by Django 5.0.14 on 2026-06-23 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('resolved', 'Resolvido'), ('escalated', 'Escalado')], default='pending', max_length=20, verbose_name='Status')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado em')),
                ('days_overdue', models.IntegerField(default=0, verbose_name='Dias em atraso')),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor devido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_alerts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Alerta de Cobranca',
                'verbose_name_plural': 'Alertas de Cobranca',
                'ordering': ['-created_at'],
            },
        ),
    ]
