# Generated by Django 5.0.14 on 2026-06-23 02:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Básico'), ('pro', 'Profissional'), ('enterprise', 'Empresarial')], default='basic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('pending', 'Pendente'), ('overdue', 'Em atraso'), ('suspended', 'Suspensa'), ('canceled', 'Cancelada')], default='active', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('yearly', 'Anual')], default='monthly', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=99.9, max_digits=10, verbose_name='Valor')),
                ('current_period_start', models.DateField(default=django.utils.timezone.now, verbose_name='Início do período')),
                ('current_period_end', models.DateField(blank=True, null=True, verbose_name='Fim do período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=20)),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('method', models.CharField(blank=True, max_length=50, verbose_name='Método')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-due_date'],
            },
        ),
    ]
