# Generated by Django 5.0.14 on 2026-06-23 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Código de barras')),
                ('unit', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('pct', 'Pacote')], default='un', max_length=10, verbose_name='Unidade')),
                ('min_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque mínimo')),
                ('max_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque máximo')),
                ('current_stock', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Estoque atual')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de custo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço de venda')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.category')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviado'), ('received', 'Recebido'), ('canceled', 'Cancelado')], default='draft', max_length=20, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Data prevista')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Recebido em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo unitário')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchaseorder')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens do Pedido',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída'), ('adjustment', 'Ajuste'), ('waste', 'Perda')], max_length=20, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Quantidade')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contato')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('cnpj', models.CharField(blank=True, max_length=20, verbose_name='CNPJ')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('tenant', 'sku')},
        ),
    ]
